base/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from base.decorators import has_permission
from base.views.business import BusinessRegister, BusinessProfile
#from easy_pdf.views import PDFTemplateView
from base.views.customer_view import CustomerView, CustomeRegisterView, CustomerRemoveView, CustomerEditView, \
    CustomerSelectView, ExportView, ImportView
from base.views.dashboard_view import Dashboard
from base.views.invoice import ProposalEvent, ProposalItemsView, ProposalView, ItemView, ItemDelete, ProposalAccept, \
    ProposalDeny, ProposalEmailSend, InvoiceView, InvoiceEvent, InvoiceEmailSend, \
    ProposalDeleteView, InvoiceDeleteView,\
    invoice_downloadpdf, proposal_downloadpdf, finish_send_proposal, finish_send_invoice
from base.views.stripe_views import StripeAuthorizeView, StripeCallbackView, StripeRenewSubscribeView, InvoiceCharge, \
    CancelSubscription, ChangeCard, SubscriptionDetails, UpdateBillingEmail, Subscribe

urlpatterns = [

    url(r'^customers/$', login_required(CustomerView.as_view()), name="customers"),
    url(r'^customers/(?P<id>\d+)/$', login_required(CustomerView.as_view()), name="customer"),
    url(r'^customers/add$', login_required(CustomeRegisterView.as_view()), name="add_customer"),
    url(r'^customers/delete/(?P<id>\d+)/$', login_required(CustomerRemoveView.as_view()), name="delete_customer"),
    url(r'^customers/edit/(?P<id>\d+)/$', login_required(CustomerEditView.as_view()), name="edit_customer"),
    url(r'^customers/list/$', login_required(CustomerSelectView.as_view()), name="customer_list"),
    url(r'^customers/export/$', login_required(ExportView.as_view()), name="customers_export"),
    url(r'^customers/import/$', login_required(ImportView.as_view()), name="customers_import"),
    url(r'^business/register$', BusinessRegister.as_view(), name="business_register"),
    url(r'^business/profile/$', login_required(BusinessProfile.as_view()), name="business_profile"),
    # url(r'^business/subscription/payment/$', login_required(PaymentOrder.as_view()), name="payment_subs"),
    url(r'^proposal/$', login_required(ProposalView.as_view()), name="proposal_list"),
    url(r'^proposal/event/$', login_required(ProposalEvent.as_view()), name="proposal_event_create"),
    url(r'^proposal/(?P<id>\d+)/event/$', login_required(ProposalEvent.as_view()), name="proposal_event_edit"),
    url(r'^proposal/(?P<id>\d+)/items/$', login_required(ProposalItemsView.as_view()), name="proposal_items_step"),
    url(r'^proposal/(?P<id>\d+)/items/list/$', login_required(ItemView.as_view()), name="proposal_items"),
    url(r'^proposal/(?P<id>\d+)/items/(?P<id_item>\d+)/$', login_required(ItemView.as_view()), name="proposal_item_edit"),
    url(r'^proposal/(?P<id>\d+)/items/(?P<id_item>\d+)/delete/$', login_required(ItemDelete.as_view()), name="proposal_item_delete"),
    url(r'^proposal/(?P<id>\d+)/$', login_required(ProposalView.as_view()), name="proposal_detalles"),
    url(r'^proposal/send/(?P<id>\d+)/$', login_required(ProposalEmailSend.as_view()), name="proposal_send"),
    url(r'^proposal/accept/(?P<pidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', ProposalAccept.as_view(), name="accept_proposal"),
    url(r'^proposal/deny/(?P<pidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', ProposalDeny.as_view(), name="deny_proposal"),
    # url(r'^proposal/accept/(?P<id>\d+)/$', login_required(ProposalAccept.as_view()), name="accept_proposal_sys"),
    url(r'^proposal/deny/(?P<id>\d+)/$',( ProposalDeny.as_view()), name="deny_proposal_sys"),
    url(r'^proposal/delete/(?P<id>\d+)/$',( ProposalDeleteView.as_view()), name="delete_proposal"),
    url(r'^proposal/download/(?P<id_proposal>\d+)/$', login_required(proposal_downloadpdf), name="proposal_download"),
    url(r'^proposal/finish_send/(?P<id_proposal>\d+)/$', login_required(finish_send_proposal), name="proposal_finish_send"),

    url(r'^invoice/$', login_required(InvoiceView.as_view()), name="invoice_list"),
    url(r'^invoice/event/$', login_required(InvoiceEvent.as_view()), name="invoice_event_create"),

    url(r'^invoice/(?P<id>\d+)/event/$', login_required(InvoiceEvent.as_view()), name="invoice_event_edit"),
    url(r'^invoice/(?P<id>\d+)/$', login_required(InvoiceView.as_view()), name="invoice_detalles"),
    url(r'^invoice/(?P<id_invoice>\d+)/items/$', login_required(ProposalItemsView.as_view()), name="invoice_items_step"),
    url(r'^invoice/send/(?P<id>\d+)/$', login_required(InvoiceEmailSend.as_view()), name="invoice_send"),
    url(r'^invoice/download/(?P<id_invoice>\d+)/$', login_required(invoice_downloadpdf), name="invoice_download"),
    # url(r'^invoice/accept/(?P<iidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', InvoiceAccept.as_view(), name="accept_invoice"),
    # url(r'^invoice/cancel/(?P<iidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', InvoiceCancell.as_view(), name="cancel_invoice"),
    url(r'^invoice/delete/(?P<id>\d+)/$',(InvoiceDeleteView.as_view()), name="delete_invoice"),
    url(r'^invoice/finish_send/(?P<id_invoice>\d+)/$', login_required(finish_send_invoice), name="invoice_finish_send"),

    url(r'^business/stripe/authorize/(?P<business_id>\d+)/$', StripeAuthorizeView.as_view(), name='connect_stripe'),
    url(r'^business/stripe/callback/$', StripeCallbackView.as_view(), name='stripe_callback'),
    url(r'^business/stripe/subscribe/$',login_required(Subscribe.as_view()), name='stripe_subscribe'),
    url(r'^business/stripe/subscribe/renew/(?P<business_id>\d+)/$', StripeRenewSubscribeView.as_view(), name='stripe_renew_subscribe'),
    url(r'^business/stripe/invoice/charge/(?P<iidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', InvoiceCharge.as_view(), name='stripe_invoice_charge'),
    url(r'^business/stripe/subscription/cancel/$',login_required(CancelSubscription.as_view()), name='cancel_subcription'),
    url(r'^business/stripe/customer/card/$',login_required(ChangeCard.as_view()), name='change_card'),
    url(r'^business/stripe/subscription/$',login_required(SubscriptionDetails.as_view()), name='subscription'),
    url(r'^business/stripe/subscription/email/$',login_required(UpdateBillingEmail.as_view()), name='change_billing_email'),
    # url(r'^business/stripe/customer/card/refresh',login_required(RefreshCard.as_view()), name='refresh_card'),
    #url(r'^pdf/$', PDFTemplateView.as_view(template_name='pdf.html',
    #                                           filename='my_pdf.pdf'), name='proposal_list_pdf'),

    # url(r'^proposal/pdf/$',(PrintPDF.as_view()), name="print_pdf"),

    # url(r'^pdf/$', genpdf, name='pdf'),
]

business_site/urls.py
__author__ = 'maykel'
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from business_site.views import WebsiteTemplate, WebsiteBasics, WebsiteGallery, WebsiteLinks, WebsiteContactUs, WebsiteCheck, WebsitePreview,\
    WebsiteCongrats, Photos, PhotosRemove, PhotosAdd, PhotosEdit, Menucategory, MenucategoryAdd, MenuAdd, MenuList, MenuEdit, Unpublish, MenuRemove, StaffList, \
    StaffAdd, StaffRemove, StaffEdit, Publish,CategorySelectView

urlpatterns = patterns('',
    # Examples:
   # url(r'^$', BusinessSiteWizard.as_view([HeadInfo, BusinessInfo, ContactInfo]), name='wizard'),

    url(r'^websiteinit', WebsiteCheck.as_view(), name='websiteinit'),
    url(r'^template', login_required(WebsiteTemplate.as_view()), name='template'),
    url(r'^basic_info', login_required(WebsiteBasics.as_view()), name='basic_info'),
    url(r'^photos/$', login_required(Photos.as_view()), name='photos'),
    url(r'^photos/add$', login_required(PhotosAdd.as_view()), name='photos_add'),
    url(r'^photos/edit/(?P<id>\d+)$', login_required(PhotosEdit.as_view()), name='photos_edit'),
    url(r'^photos/remove/(?P<id>\d+)$', login_required(PhotosRemove.as_view()), name='photos_remove'),

    url(r'^gallery', login_required(WebsiteGallery.as_view()), name='gallery'),
    url(r'^category$', Menucategory.as_view(), name='category'),
    url(r'^category/add$', MenucategoryAdd.as_view(), name='add_category'),
    url(r'^category/list/(?P<id>\d+)', CategorySelectView.as_view(), name="category_list"),
    url(r'^menu$', MenuList.as_view(), name='menu'),
    url(r'^menu/add$', MenuAdd.as_view(), name='add_menu'),
    url(r'^menu/edit/(?P<id>\d+)$', MenuEdit.as_view(), name='edit_menu'),
    url(r'^menu/remove/(?P<id>\d+)$', MenuRemove.as_view(), name='remove_menu'),
    url(r'^staffandservice$', login_required(StaffList.as_view()), name='staffandservice'),
    url(r'^staffandservice/add$', login_required(StaffAdd.as_view()), name='add_staffandservice'),
    url(r'^staffandservice/remove/(?P<id>\d+)$', StaffRemove.as_view(), name='remove_staff'),
    url(r'^staffandservice/edit/(?P<id>\d+)$', StaffEdit.as_view(), name='edit_staff'),
    url(r'^links', login_required(WebsiteLinks.as_view()), name='links'),
    url(r'^contactus',login_required(WebsiteContactUs.as_view()), name='contactus'),
    url(r'^preview', login_required(WebsitePreview.as_view()), name='preview'),
    url(r'^congrats', login_required(WebsiteCongrats.as_view()), name='congrats'),
    url(r'^unpublish', Unpublish.as_view(), name='unpublish'),
    url(r'^publish', Publish.as_view(), name='publish'),
)

caterfull/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout_then_login, password_reset_done, password_reset_complete

from base.views.account import password_change_done, ConfirmEmailView, password_change, password_reset, password_reset_confirm
from base.views.dashboard_view import Dashboard

urlpatterns = [
                  url(r'^$', login_required(Dashboard), name="dashboard"),
                  url(r'^admin/', admin.site.urls),
                  # url(r'^accounts/login/$', login, {'template_name': 'base/login.html','authentication_form':CaterAuthenticationForm}, name='login'),
                  url(r'^accounts/login/$', login, {'template_name': 'base/login.html'}, name='login'),
                  url(r'^accounts/logout/$', logout_then_login, name="logout"),
                  # url(r'^accounts/password_reset/$', password_reset,{'template_name':'base/password_reset.html'}, name='password_reset'),
                  url(r'^accounts/password_reset/$', password_reset, name='password_reset'),
                  # url(r'^accounts/password_change/$', password_change,{'template_name':'base/password_change.html'}, name="password_change"),
                  url(r'^accounts/password_change/$', password_change, name="password_change"),
                  url(r'^accounts/password_change/done/$', password_change_done, name="password_change_done"),
                  url(r'^accounts/password_reset/done/', password_reset_done,
                      {'template_name': 'base/password_reset_done.html'}, name="password_reset_done"),
                  # url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name':'base/password_reset_confirm.html'}, name="password_reset_confirm"),
                  url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      password_reset_confirm, name="password_reset_confirm"),
                  url(r'^accounts/reset/done/', password_reset_complete,
                      {'template_name': 'base/password_reset_complete.html'}, name="password_reset_complete"),
                  url(
                      r'^accounts/registration_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      ConfirmEmailView.as_view(), name="registration_confirm"),
                  # url('^',include('django.contrib.auth.urls')),
                  url(r'^stripe/', include('stripe_cater.urls')),
                  url(r'^site/', include('business_site.urls')),
                  url(r'^', include('base.urls'))
              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# url(r'^password_change/$', views.password_change, name='password_change'),
#    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
#    url(r'^password_reset/$', views.password_reset, name='password_reset'),
#    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
#    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
#        views.password_reset_confirm, name='password_reset_confirm'),
#    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),

business_site/models.py
from django.conf import settings
from django.db import models
from base.models import Business
# Create your models here.


class Website(models.Model):
    template = models.IntegerField(default=1)#Ahora este campo es estatico
    business = models.ForeignKey(Business, default=0, related_name='website')

    def __str__(self):
        return self.business.name



class WebDomain(models.Model):
    domain = models.CharField(max_length=50, blank=False)
    website = models.OneToOneField(Website, default=0)

    def __str__(self):
        return self.domain


class BasicInfo(models.Model):
    logo = models.FileField(upload_to='photos', null=True)
    description = models.CharField(max_length=250, blank=False)
    website = models.OneToOneField(Website, default=0)


class Gallery(models.Model):
    comments = models.CharField(max_length=50, blank=True)
    # background = models.FileField(upload_to=settings.MEDIA_ROOT+'/photos', blank=False)
    website = models.OneToOneField(Website)


class Photo(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    image = models.FileField(upload_to='photos', blank=False)
    asbackground = models.BooleanField(default=False)
    gallery = models.ForeignKey(Gallery)

class Category(models.Model):
    description = models.CharField(max_length=100)
    website = models.ForeignKey(Website)

    class Meta:
        unique_together = (('description','website'),)

    def __str__(self):
        return self.description

class Menu(models.Model):
    name = models.CharField(max_length=150, null=False)
    description = models.TextField(max_length=150, null=True, blank=True)
    # price = models.FloatField(default=0.00, null=False)
    image = models.FileField(upload_to='photos')
    comments = models.TextField(max_length=200, null=True, blank=True)
    category = models.ForeignKey(Category)

class MenuPrice(models.Model):
    min = models.IntegerField(null=False)
    max = models.IntegerField(null=False)
    price = models.FloatField(null=False, default=0.00)
    menu = models.ForeignKey(Menu)
    def get_total(self):
        return self.max*self.price

class StaffServices(models.Model):
    service = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(max_length=250, null=True, blank=True)
    image = models.FileField(upload_to='photos')
    price = models.FloatField(default=0.00, null=False)
    website = models.ForeignKey(Website)


class Links(models.Model):
    twitter = models.URLField(default="twitter.com", null=True)
    instagram = models.URLField(default="instagram.com", null=True)
    facebookpage = models.URLField(default="facebook.com", null=True)
    yelp = models.URLField(default="yelp.com", null=True)
    gplus = models.URLField(default="gplus.com", null=True)
    website = models.OneToOneField(Website)


class ContactUs(models.Model):
    phone = models.CharField(max_length=15,null=False)
    email = models.EmailField()
    address = models.CharField(max_length=100, null=True)
    website = models.OneToOneField(Website)


class WebsiteControl(models.Model):
    status = models.IntegerField(default=0)#(0-create, 1-template, 2-basic, 3-gallery,4-Menu, 5-Staff, 6-links, 7-contact, 8-publish)
    website = models.OneToOneField(Website)

business_site/templates/business_site/menu/category.html
{% extends 'base2.html' %}
{% load admin_static %}
{% load staticfiles %}
{% load i18n admin_static %}
{% load widget_tweaks %}

{% block title %} Website - AddCategory {% endblock %}
{% block main_content %}
    {% for cat in categorys %}
        <div>{{ cat.id }}{{ cat.description }}</div>
    {% endfor %}
{% endblock %}

business_site/templates/business_site/menu/category_add.html
{% extends 'base2.html' %}
{% load admin_static %}
{% load staticfiles %}
{% load i18n admin_static %}
{% load widget_tweaks %}

{% block title %} Website - AddCategory {% endblock %}
{% block main_content %}
    {% include 'business_site/menu/category_add_form.html' %}
{% endblock %}

business_site/templates/business_site/menu/category_add_form.html
{% load widget_tweaks %}
{#<form action="" method="post" id="form_category">#}
{#    {% csrf_token %}#}
{##}
{#    {{ form }}#}
{#    <input type="submit"/>#}
{#</form>#}

<form action="category/add" method="post" id="form_category" class="form-horizontal">
    {% csrf_token %}

    <div class="form-group {% if form_category.description.errors %} has-error {% endif %}">
        <label for="description" class=" col-xs-12"> Nueva categoría <span class="required-field">*</span></label>

        <div class="col-xs-12 col-sm-9">
            {% render_field form_category.description class="form-control" %}
        </div>
         {% for error in  form_category.description.errors %}
            <div class="text-validation-error"><i class="fa fa-warning"></i> {{ error }} </div>
        {% endfor %}
        <div class="display-inline pull-right" style="margin-right: 15px">
            <button type="button" class="btn btn-success btn-flat" id="submit_category"><i class="fa fa-check"></i>
            </button>
            <button type="button" class="btn btn-default btn-flat" id="reset_category"><i class="fa fa-close"></i>
            </button>
        </div>

    </div>

</form>
<script>
    $(document).ready(function () {
        $("#reset_category").click(function () {
            $("#category_container").empty();
            $("#category_container").addClass('collapse');
        });

        $("#submit_category").click(function () {
            var form_data = $("#form_category").serialize();
            set_csrf_token();

            return $.ajax({
                type: "POST",
                url: 'category/add',
                data: form_data,
                success: function (data, status_code) {
{#                    console.debug(status_code);#}
{#                    console.debug(data);#}
                    toastr.success("Se ha agregado correctamente la categoría");

                    var url = 'category/list/'+data.id;

                    $.get(url,{id:data.id}, function (data) {
                        $('#field_container').empty().append(data);
                        $('#category_container').addClass('collapse');
                        $('#category_container #id_description').val('');
                    });
                },
                error: function (response) {
{#                    console.debug(response);#}

                     $("#form_category .form-group").addClass('has-error');
{#                     $("#form_category .form-group").addClass('has-error');#}

                }
            });
        });


    });

    function set_csrf_token() {
        var csrftoken = $('input[name="csrfmiddlewaretoken"]').val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    //alert(csrftoken);
                }
            }
        });
    }

</script>

business_site/templates/business_site/menu/menu_add.html
{% load admin_static %}
{% load staticfiles %}
{% load i18n admin_static %}
{% load widget_tweaks %}


<form action="" method="post" enctype="multipart/form-data" id="menu_form">
    {% csrf_token %}

    <div class="form-group col-xs-12 col-sm-3 {% if form.category.errors %} has-error {% endif %} menu-category-container">
        <label> {{ form.category.label }} <span class="required-field">*</span> </label>

        <div id="field_container">{% render_field form.category class="form-control" %}</div>

        <button id="add_category" class="btn btn-success btn-flat add from-event"
                style="margin-left: -16px; height: 34px"
                type="button"><i class="fa fa-plus"></i></button>
        {% for error in  form.category.errors %}
            <div class="text-validation-error" style="clear:both"><i class="fa fa-warning"></i> {% trans error %} </div>
        {% endfor %}
    </div>

    <div class="form-group col-xs-12  col-sm-4 {% if form.image.errors %} has-error {% endif %}">
        <label> {{ form.image.label }} </label>
        {% render_field form.image class="form-control" %}
        {% for error in  form.image.errors %}
            <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
        {% endfor %}
    </div>
    <div id="items_list" class="col-xs-12 col-sm-5 form-group pull-right">
     <div id="item_price" class="form-group col-xs-12 no-padding">
                <div class="form-group col-xs-3 no-padding-right">
                    <label> min <span class="required-field">*</span> </label>
                    {% render_field form.min class="form-control" type='number'  name="ni" value="1" readonly="readonly" %}
                </div>
                <div class="form-group col-xs-3 no-padding-right">
                    <label> max <span class="required-field">*</span> </label>
                    {% render_field form.max class="form-control col-xs-4" name="na" onkeypress="return soloLetras(event)" type='number' value="2" %}
                </div>
                <div class="form-group col-xs-3 no-padding-right">
                    <label> precio <span class="required-field">*</span> </label>
                    {% render_field form.price class="form-control col-xs-4" name="no" onkeypress="return soloLetras(event)" type='number' value="0.00" %}
                    {% for error in  form.price.errors %}
                        <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
                    {% endfor %}
                </div>

                <div class="form-group col-xs-3 no-padding">
                    <label class="col-xs-12" style="height: 19px; display: block"> </label>
                    <button type="button" id="plus_item" name="plus_item" onclick="Adicionar()"  class="btn btn-success btn-flat"><i class="fa fa-plus"></i> </button>
                    <button type='button'  name='less_item' onclick="Eliminar()"   class="btn btn-danger btn-flat less_item"><i class="fa fa-minus"></i> </button>
                </div>
<h4 class="rango">   Rangos de precios</h4>

                {#              <input type="button" value="-" id="less_item" name="less_item"/>#}
            </div>
     {% if list %}
     <script>
        $(document).ready(function(){
           if($('.max_value').last().val()!=0)
           {
             $('#id_min').val(parseInt($('.max_value').last().val())+1);
             $('#id_max').val(parseInt($('.max_value').last().val())+2);
             $('#id_price').val(parseFloat($('.price_value').last().val()));
           }
        });
        </script>
            {% for item in list %}
                <div id='item_price' class='form-group col-xs-12 item_price no-padding'>
                    <div class="form-group col-xs-3 no-padding-right">
                        <input class='form-control min_value' id='min_value' readonly='readonly' value='{{ item.min }}'
                               name='min' rows='5' type='number'>

                    </div>
                    <div class="form-group col-xs-3 no-padding-right">

                        <input class='form-control max_value' id='max_value' readonly='readonly' name='max'
                               type='number'
                               rows='5' value='{{ item.max }}'>

                    </div>
                    <div class="form-group col-xs-3 no-padding-right">
                        <input class='form-control price_value' id='price_value' name='price'
                               type='number' rows='5' value='{{ item.price }}' step='0.01' min='0'>
                        {% for error in  form.price.errors %}
                            <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="form-group col-xs-12  col-sm-7 {% if form.image.errors %} has-error {% endif %} collapse"
         id="category_container">
        <label> {{ form.image.label }} </label>
        {% render_field form.image class="form-control" %}
        {% for error in  form.image.errors %}
            <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
        {% endfor %}
    </div>

    <div class="form-group col-xs-12 col-sm-7 {% if form.name.errors %} has-error {% endif %}">
        <label> {{ form.name.label }} <span class="required-field">*</span> </label>
        {% render_field form.name class="form-control" %}
        {% for error in  form.name.errors %}
            <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
        {% endfor %}
    </div>
    <div class="form-group col-xs-12  col-sm-7 {% if form.description.errors %} has-error {% endif %}">
        <label> {{ form.description.label }} </label>
        {% render_field form.description class="form-control" rows="3" %}
        {% for error in  form.description.errors %}
            <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
        {% endfor %}
    </div>
    <div class="form-group col-xs-12  col-sm-7 {% if form.comments.errors %} has-error {% endif %}">
        <label> {{ form.comments.label }} </label>
        {% render_field form.comments class="form-control" rows="3" %}
        {% for error in  form.comments.errors %}
            <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
        {% endfor %}
    </div>
    <span id="error" style="display: none">{{ error }}</span>
    <span id="index" style="display: none">{{ index }}</span>

    <div class="clearfix"></div>
    {#    {{ form }}#}
    {#        <input type="submit"/>#}
</form>
<script>
    $(document).ready(function(){
        if ($('#error').text() != "") {
            toastr.error($('#error').text());
        }
        if ($('#index').text() != "") {
            $($('.item_price')[[parseInt($('#index').text())]].children[2].children.price_value).focus()
        }

      $('#saveAdd').click(function(){
         $('.item_price').remove();
          $('#id_min').val('1');
          $('#id_max').val('2');
           $('#id_price').val('0.00');
      });

    });
     $("#add_category").click(function(){
            $.get({
            url:'category/add',
            success:function(response){
                $("#category_container").empty().append(response);
                $("#category_container").removeClass('collapse');
                $("#form_category #id_description").focus();
            },
            error:function(response){

            }
        });
    });
    $("#reset_category").click(function(){
         $("#category_container").empty();  $("#category_container").addClass('collapse');
    });
</script>
{% block js_block_one %}
    <script type="text/javascript" src="{% static 'js/itemprice.js' %}"></script>
{% endblock %}

business_site/templates/business_site/menu/select.html
{% load widget_tweaks %}
{% load i18n admin_static %}

    {% render_field form.category class="form-control" %}

{#{% for error in  form.category.errors %}#}
{#    <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>#}
{#{% endfor %}#}